using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class AudioSetting_Scripts : MonoBehaviour
{

    //ã‚¹ãƒ©ã‚¤ãƒ€ãƒ¼
    private Slider BGMvolumeSlider;
    private Slider SEvolumeSlider;

    //ã‚ªãƒ¼ãƒ‡ã‚£ã‚ªã‚½ãƒ¼ã‚¹
    public GameObject BGMaudioSource;
    public GameObject SEaudioSource;

    // BGM SEãƒªã‚¹ãƒˆ
    public List<AudioClip> BGMs;
    public List<AudioClip> SEs;

    //éŸ³é‡ç®¡ç†ã‚·ã‚¹ãƒ†ãƒ ãŒé–‹ã‹ã‚Œã¦ã„ã‚‹ã‹ã©ã†ã‹
    public bool Opened_Audio_Setting = false;

    void Start()
    {
        //ã‚·ãƒ¼ãƒ³å†…ã‹ã‚‰Sliderã‚’æ¢ã—ã¦å–å¾—
        BGMvolumeSlider = GameObject.Find("BGMvolumeSlider").GetComponent<Slider>();
        SEvolumeSlider = GameObject.Find("SEvolumeSlider").GetComponent<Slider>();

        //ä¿å­˜ã•ã‚ŒãŸéŸ³é‡ã‚’åæ˜ 
        BGMvolumeSlider.value = Update_Volume.BGMsliderValue;
        SEvolumeSlider.value = Update_Volume.SEsliderValue;

    }

    void Update()
    {
        //ã‚¹ãƒ©ã‚¤ãƒ€ãƒ¼ã®å€¤ã‚’å–å¾—
        Update_Volume.BGMsliderValue = BGMvolumeSlider.value;
        Update_Volume.SEsliderValue = SEvolumeSlider.value;

        //ã‚ªãƒ¼ãƒ‡ã‚£ã‚ªã®éŸ³é‡è¨­å®š
        BGMaudioSource.GetComponent<AudioSource>().volume = Update_Volume.BGMsliderValue;
        SEaudioSource.GetComponent<AudioSource>().volume = Update_Volume.SEsliderValue;

        //ã‚¹ãƒ©ã‚¤ãƒ€ãƒ¼ã®å€¤ãŒå¤‰æ›´ã•ã‚ŒãŸæ™‚ã®å‡¦ç†ã‚’è¨˜éŒ²
        BGMvolumeSlider.onValueChanged.AddListener(ChangeVolumeBGM);
        SEvolumeSlider.onValueChanged.AddListener(ChangeVolumeSE);

        //ã‚­ãƒ¼ãŒæŠ¼ã•ã‚ŒãŸã¨ãã®å‡¦ç†
        if (Input.GetKeyDown(KeyCode.T) && !Opened_Audio_Setting)
        {
            Debug.Log("OPEN");
            Open_Audio_Setting();
        }
        else if (Input.GetKeyDown(KeyCode.T) && Opened_Audio_Setting)
        {
            Debug.Log("CLOSE");
            Close_Audio_Setting();
        }
    }

    void ChangeVolumeBGM(float newVolume)
    {
        //ã‚¹ãƒ©ã‚¤ãƒ€ãƒ¼ã®å€¤ã«ã‚ˆã£ã¦éŸ³é‡ã‚’å¤‰æ›´
        BGMaudioSource.GetComponent<AudioSource>().volume = newVolume;
    }
    void ChangeVolumeSE(float newVolume)
    {
        //ã‚¹ãƒ©ã‚¤ãƒ€ãƒ¼ã®å€¤ã«ã‚ˆã£ã¦éŸ³é‡ã‚’å¤‰æ›´
        SEaudioSource.GetComponent<AudioSource>().volume = newVolume;
    }

    void PauseGame()
    {
        //ã‚²ãƒ¼ãƒ ã®æ™‚é–“åœæ­¢
        Time.timeScale = 0f;
    }

    void ResumeGame()
    {
        //ã‚²ãƒ¼ãƒ ã®æ™‚é–“ã‚’å†é–‹
        Time.timeScale = 1f;
    }

    //Opened_Audio_SettingãŒFalseã®ã¨ãã«å®Ÿè¡Œã•ã‚Œã‚‹
    //éŸ³é‡èª¿ç¯€ç”»é¢ã‚’é–‹ã
    public void Open_Audio_Setting()
    {
        if (!Opened_Audio_Setting)
        {
            gameObject.transform.position = new Vector3(gameObject.transform.position.x, gameObject.transform.position.y - 250f, gameObject.transform.position.z);
            Opened_Audio_Setting = true;
            PauseGame();
        }
    }

    //ğŸ‘‡Opened_Audio_SettingãŒTrueã®æ™‚ã«å®Ÿè¡Œã•ã‚Œã‚‹
    //éŸ³é‡èª¿ç¯€ç”»é¢ã‚’é–‰ã˜ã‚‹
    public void Close_Audio_Setting()
    {
        if (Opened_Audio_Setting)
        {
            gameObject.transform.position = new Vector3(gameObject.transform.position.x, gameObject.transform.position.y + 250f, gameObject.transform.position.z);
            Opened_Audio_Setting = false;
            ResumeGame();
        }
    }

    //SEã‚’é³´ã‚‰ã™
    public void Play_SE(int seIndex)
    {
        SEaudioSource.GetComponent<AudioSource>().clip = SEs[seIndex];
        SEaudioSource.GetComponent<AudioSource>().Play();
    }
    //BGMã‚’é³´ã‚‰ã™
    public void Play_BGM(int bgmIndex)
    {
        BGMaudioSource.GetComponent<AudioSource>().clip = BGMs[bgmIndex];
        BGMaudioSource.GetComponent<AudioSource>().Play();
    }

}
